### PR TITLE
trying to make it 10.12 working.. they got rid of QTKit

### PR DESCRIPTION
**Pull request by pascalwhoop**
@Hunter-Dolan Hi. You seem to have worked on this about 6 months ago pulling it up to 10.11. Now I'm trying to save my families tapes and it doesn't work on 10.12. 

I got the same chip as you I believe `ECVFushicaiDevice`.

I tried to port the QT stuff over to AVFoundation afaik, but since this is my first time touching C code I am struggling. 

currently, the app builds on my sierra machine and starts up, once I press play a bunch of warnings pop out. See log below. 

If you care to help or point me in the direction to go I'd appreaciate it. otherwise it might be cheaper for me to buy a linux machine and run it on there. for some reason I cannot connect the stick to my VM that's why i'm trying to make it work on osx

```
2016-12-27 14:03:28.977059 EasyCapViewer[10620:143626] USB Devices: (
    "(05ac:8006) Apple Inc. - Root Hub Simulation Simulation",
    "(05ac:8006) Apple Inc. - Root Hub Simulation Simulation",
    "(05ac:8007) Apple Inc. - Root Hub Simulation Simulation",
    "(8087:0024) ???? - ????",
    "(8087:0024) ???? - ????",
    "(1b71:3002) fushicai - usbtv007",
    "(0424:2512) ???? - ????",
    "(0a5c:4500) Apple Inc. - BRCM20702 Hub",
    "(05ac:0263) Apple Inc. - Apple Internal Keyboard / Trackpad",
    "(05ac:8286) Apple Inc. - Bluetooth USB Host Controller",
    "(05ac:8510) Apple Inc. - FaceTime HD Camera (Built-in)"
)
IT LOADED YAY2016-12-27 14:03:31.219651 EasyCapViewer[10620:143626] [EasyCapViewer] ImageIO: _IIOImageSourceCreateWithData:3282: data parameter is nil
2016-12-27 14:04:29.940271 EasyCapViewer[10620:144240] Starting device usbtv007.
2016-12-27 14:04:34.133562 EasyCapViewer[10620:144240] Line 127, read 0000: Expected <013a>, received <0161>
2016-12-27 14:04:34.148712 EasyCapViewer[10620:144240] Line 129, read 0000: Expected <016fd00c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c>, received <00660101 6814141f 1f024009 040d0000 00711b01 30103130 6d6f6f6e 73000000 00>
2016-12-27 14:04:34.160938 EasyCapViewer[10620:144240] Line 130, read 0020: Expected <016fd00c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c>, received <00000000 00000000 00000000 00000000 00000000 26555342 2053746f 72616765 20>
2016-12-27 14:04:34.173211 EasyCapViewer[10620:144240] Line 131, read 0040: Expected <016fd00c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c>, received <00446576 69636500 00000000 00000000 0000001a 33303030 30303030 30303031 00>
2016-12-27 14:04:34.185357 EasyCapViewer[10620:144240] Line 132, read 0060: Expected <016fd00c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c>, received <00000000 00000000 00000000 00000000 00002d71 1b023012 66757368 69636169 00>
2016-12-27 14:04:34.197507 EasyCapViewer[10620:144240] Line 133, read 0080: Expected <016fd00c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c>, received <00000000 00000000 00000000 00000000 00000000 00001275 73627476 30303700 00>
2016-12-27 14:04:34.209763 EasyCapViewer[10620:144240] Line 134, read 00a0: Expected <016fd00c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c>, received <00000000 00000000 00000000 00000000 00000000 001a3330 30303030 30303030 30>
2016-12-27 14:04:34.222018 EasyCapViewer[10620:144240] Line 135, read 00c0: Expected <016fd00c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c>, received <00320000 00000000 00000000 00000000 00000000 58030300 00000000 00a3f833 94>
2016-12-27 14:04:34.234204 EasyCapViewer[10620:144240] Line 136, read 00e0: Expected <016fd00c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c0c0c0c 0c>, received <00f8877a c2007bc2 027ec201 7fc20bdc c1000000 00000000 00000000 00000000 00>
2016-12-27 14:04:34.315137 EasyCapViewer[10620:144240] Line 336, read c244: Expected <11>, received <12>
2016-12-27 14:04:34.316659 EasyCapViewer[10620:144240] Line 338, read c244: Expected <11>, received <12>
2016-12-27 14:04:38.466845 EasyCapViewer[10620:144240] -[ECVCaptureDevice controlRequestWithType:request:value:index:length:data:]:377 error: kIOReturnNotPermitted
2016-12-27 14:04:38.470492 EasyCapViewer[10620:144240] Line 369, read c244: Expected <11>, received <12>
2016-12-27 14:04:38.471353 EasyCapViewer[10620:144240] Line 370, read c246: Expected <d0>, received <00>
2016-12-27 14:04:38.472112 EasyCapViewer[10620:144240] Line 371, read c244: Expected <11>, received <12>
2016-12-27 14:04:38.472844 EasyCapViewer[10620:144240] Line 372, read c245: Expected <c0>, received <90>
2016-12-27 14:04:38.474384 EasyCapViewer[10620:144240] Line 374, read c243: Expected <00>, received <80>
2016-12-27 14:04:38.475265 EasyCapViewer[10620:144240] Line 375, read c240: Expected <82>, received <00>
2016-12-27 14:04:38.476575 EasyCapViewer[10620:144240] Line 377, read c239: Expected <60>, received <42>
2016-12-27 14:04:38.477526 EasyCapViewer[10620:144240] Line 378, read c244: Expected <11>, received <12>
2016-12-27 14:04:38.478540 EasyCapViewer[10620:144240] Line 379, read c246: Expected <d0>, received <00>
2016-12-27 14:04:38.479377 EasyCapViewer[10620:144240] Line 380, read c244: Expected <11>, received <12>
2016-12-27 14:04:38.480115 EasyCapViewer[10620:144240] Line 381, read c245: Expected <c0>, received <90>
2016-12-27 14:04:38.507208 EasyCapViewer[10620:144240] Line 383, read c244: Expected <11>, received <12>
2016-12-27 14:04:38.507964 EasyCapViewer[10620:144240] Line 384, read c245: Expected <c0>, received <90>
2016-12-27 14:04:38.508666 EasyCapViewer[10620:144240] Line 385, read c244: Expected <11>, received <12>
2016-12-27 14:04:38.510484 EasyCapViewer[10620:144240] Line 388, read c243: Expected <00>, received <80>
2016-12-27 14:04:38.511665 EasyCapViewer[10620:144240] Line 390, read c240: Expected <82>, received <00>
```

### CODE REVIEW

**Comment by Hunter-Dolan** [comment]
Hey, thanks for your contribution. Those warnings are normal, especially on the Fushicai devices. I just tried to run your fork and I did get a crash, but it looks like it was on a piece in the code that dealt with audio conversion.

I commented out line 131 and line 132 on ECVAudioPipe.m, and plugged in a device, and was able to get picture.

I am very curious to hear if you were getting a similar crash. To the best of my knowledge, audio does not work with Fushicai devices.

If you are running this and only getting a black screen be sure:

1) The device you are trying to see the picture on is powered up and connected to your EasyCap Device.

2) EasyCapViewer is configured to use the "Composite" source. (Click EasyCapViewer > Configure Device > Source) and not "S-Video".

Cheers!

PS: I don't have write access to this repository, so whether or not this will get merged is up to @btrask.

**Comment by Hunter-Dolan** [comment]
I've attached a built binary with the code provided above (with the two lines commented out). Should this not be merged for what ever reason, it will at least provide a way for people to use their device.

[EasyCapViewer.zip](https://github.com/btrask/EasyCapViewer/files/674202/EasyCapViewer.zip)

**Comment by pascalwhoop** [comment]
nope for me it stays black even though I tried both your and my self built code. commented out the two lines but never got an error for them anyways. What system are you on? the input is composite but the actual cable connected is svideo for me, how about you? I am on macos 10.12.2

**Comment by Hunter-Dolan** [comment]
I am on 10.12.1 on a MacBook Pro (2013), i'll try upgrading tonight and see
if that breaks it for me. I cannot imagine it would though.

I have EasyCapViewer configured to use the Composite source and am
connecting my EasyCap it to a wireless video receiver via RCA connectors.

It's possible that the issue you are having is because you're connected
over S-Video. Of course, also try setting the source to S-Video. It may be
worth trying the RCA connectors if possible.

It's all a big trial and error process unfortunately. A lot of these
devices have horrible or non-existent documentation, so its hit or miss.

- Hunter

On December 27, 2016 at 9:12:26 AM, Pascal Brokmeier (
notifications@github.com) wrote:

nope for me it stays black even though I tried both your and my self built
code. commented out the two lines but never got an error for them anyways.
What system are you on? the input is composite but the actual cable
connected is svideo for me, how about you? I am on macos 10.12.2

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/btrask/EasyCapViewer/pull/2#issuecomment-269331102>,
or mute
the thread

**Comment by vicegold** [comment]
I can get a picture with both S-Video and Composite now, thanks for the fixes Hunter and Pascal. Just audio doesn't work, but i don't need that at the moment. Thanks!

@pascal Don't forget to put the sliders for Contrast, Brightness and so on to the middle of the bar. If you let them like it is at program start you won't see anything.

**Comment by pascalwhoop** [comment]
Thanks now it works for me too I just didn't set the brightness properly.
Audio will be fine with the microphone in of the laptop. Enjoy New Year's
Eve everyone

**Comment by pascalwhoop** [comment]
@Hunter-Dolan another question: since the macbook doesn't accept a line-in in the headphone jack, nor a normal microphone cable, how do you get the sound transferred without a usb to microphone adapter? Do you have any ideas on getting the audio to work? It worked on the linux kernel with the usbtv007 ([wiki](https://linuxtv.org/wiki/index.php/Easycap#USBTV007_EasyCAP)) so i'm sure we could get it to work with osx as well?

**Comment by JazzzzX** [comment]
I just copied 10.11 sdk to my xcode8 sdk directory and the app builds and works perfectly in 10.12 Sierra without any issues,no need for avfoundation porting. (In build setting change base sdk option from latest to 10.11)

I have a "(1b71:3002) fushicai - usbtv007" device,So no Audio..!!! Any way guys for audio input ?

**Comment by btrask** [comment]
Thanks @pascalwhoop, @Hunter-Dolan!

**Comment by tristan-k** [comment]
Is the binary from @Hunter-Dolan the most recent version which works with Sierra?

**Comment by garfieldnate** [comment]
I have OS 10.12.3, but the version posted above still didn't make audio work for me :(. It doesn't crash, though, like the last release does. Here's the info from my USB device:

USB 2.0 Video Capture Controller:

  Product ID:	0x0408
  Vendor ID:	0x05e1  (Syntek Design Technology Inc.)
  Version:	0.05
  Speed:	Up to 480 Mb/sec
  Manufacturer:	Syntek Semiconductor
  Location ID:	0x14200000 / 8
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0

I'd be glad to provide any debugging information, if there is any way for me to get it.

**Comment by madebyck** [comment]
Hi all,

Just wondering if anyone else is having an issue with recording (I can view the video fine). When ever I click 'start recording' I get a message telling me to re-open easycap viewer in 32-bit mode?

Running 10.12.6 and I've tried it on a 2007 macbook pro and a 2016 macbook pro. Any ideas?

**Comment by Hunter-Dolan** [comment]
Hey @MadeByCK, this should probably be moved to a separate issue so that someone can take a look at it.

However a quick (and dirty) fix in the mean time would be to use the screen recording feature in Quick Time to capture the video output.

**Comment by madebyck** [comment]
hey @Hunter-Dolan, thanks for the help. Not sure I can create a new issue on this project, the button isnt there - any help creating a new issue would really be helping me out!

I've tried working it out in xcode myself but I seem to break more than I fix

**Comment by captainjack64** [comment]
@MadeByCK Did you ever get to the bottom of this? Cannot capture - moaning about 32 bit mode.

**Comment by arkwise** [comment]
sick works in big sure just fine :)

**Pull request merged**
