### PR TITLE
Hacked together 10.11 Support (Dirty) / Added PAL to Fushicai Device

### PR DESCRIPTION
**Pull request by Hunter-Dolan**
This is a relatively dirty patch. It only fixes EasyCapViewer, but allows it to compile and run on 10.11.

In addition I've enabled PAL on Fushicai devices, appears to be working without modification.

### CODE REVIEW

**Comment by Hunter-Dolan** [comment]
Worth noting that any reference to 10.10 should be replaced with 10.11. Can't keep the version numbers strait.

**Comment by btrask** [comment]
Sorry for the delay, and thanks!

**Comment by dmitrybelsky** [comment]
Sorry, but could you provide some help how to compile it or use it?

**Comment by Hunter-Dolan** [comment]
Sure:
1. Ensure that you have the latest version of Xcode + The latest OS X SDK
2. Clone the project and open up EasyCapViewer.xcodeproj
3. On the target selector, (drop dropdown on the left hand side of Xcode [by default it should say "Everything"]),  select "EasyCapViewer". The "EVComponent" target needs more work than its worth (at least for me) to work on 10.11.
4. Hit the Run button

The project should build and EasyCap should launch without issue.

If it doesn't, I'd recommend opening a separate issue on Github with the exact error message you're receiving. No point in tacking it onto here.

**Comment by dmitrybelsky** [comment]
Thanks!

**Pull request merged**
